### ISSUE TITLE
[Profiler] Replace the current graph component with new one

### ISSUE THREAD

**Issue by Ghislain1** [Ghislain1/nf-tools#5]
**TODO**
- Find New Compoment for graph ?
- Provide usage of the new  graph compoment

**How to test it**

1. Start app
2. Open any Log file
3. App should display a new window with Gabage collection, Prorfiler statistic info ...
4. Press Histogram Button...

**Comment by Ghislain1** [comment]
@josesimoes  it will be nice if you push (or send me) an example (or many) of **nanoProfiler log files**  as raw data for testing

**Comment by josesimoes** [comment]
Sure! Here they are:

[profile-20230907180435.log](https://github.com/Ghislain1/nf-tools/files/12881758/profile-20230907180435.log)
[profile-20230907173402.log](https://github.com/Ghislain1/nf-too
[tmp379E.log](https://github.com/Ghislain1/nf-tools/files/12881770/tmp3
[tmpA7FD.log](https://github.com/Ghislain1/nf-tools/files/12881772/tmpA7FD.log)
